steps:
# This step builds the container image.
- name: 'gcr.io/$PROJECT_ID/github.com/dotslashbin/tool_api'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/github.com/dotslashbin/tool_api:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'push gcr.io/$PROJECT_ID/toolapi'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/github.com/dotslashbin/tool_api:$SHORT_SHA'